name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipx
        run: python -m pip install --upgrade pipx

      - name: Install uv via pipx
        run: pipx install uv

      - name: Initialize venv
        run: uv venv

      - name: uv sync
        run: uv sync --all-groups

      - name: Run tests
        run: uv run pytest -v --maxfail=1 --disable-warnings
